### ISSUE TITLE
Failed to resolve entry for package "@open-data-v/base". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by shilianmalaxiangguo** [AnsGoo/openDataV#143]
遇到的问题

启动项目报错
` [vite] Internal server error: Failed to resolve entry for package "@open-data-v/designer". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: D:/UGit/openBi/examples/src/index.ts
      at packageEntryFailure (file:///D:/UGit/openBi/node_modules/.pnpm/vite@4.5.3_@types+node@16.18.104_less@4.2.0_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28725:11)
      at resolvePackageEntry (file:///D:/UGit/openBi/node_modules/.pnpm/vite@4.5.3_@types+node@16.18.104_less@4.2.0_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28722:5)
      at tryNodeResolve (file:///D:/UGit/openBi/node_modules/.pnpm/vite@4.5.3_@types+node@16.18.104_less@4.2.0_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28453:20)
      at Context.resolveId (file:///D:/UGit/openBi/node_modules/.pnpm/vite@4.5.3_@types+node@16.18.104_less@4.2.0_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28212:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///D:/UGit/openBi/node_modules/.pnpm/vite@4.5.3_@types+node@16.18.104_less@4.2.0_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44276:32)
      at async TransformContext.resolve (file:///D:/UGit/openBi/node_modules/.pnpm/vite@4.5.3_@types+node@16.18.104_less@4.2.0_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:43992:23)
      at async normalizeUrl (file:///D:/UGit/openBi/node_modules/.pnpm/vite@4.5.3_@types+node@16.18.104_less@4.2.0_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41836:34)
      at async file:///D:/UGit/openBi/node_modules/.pnpm/vite@4.5.3_@types+node@16.18.104_less@4.2.0_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:41998:47
      at async Promise.all (index 8) (x2)
Failed to resolve entry for package "@open-data-v/designer". The package may have incorrect main/module/exports specified in its package.json.
Failed to resolve entry for package "@open-data-v/designer". The package may have incorrect main/module/exports specified in its package.json. (x2)
Failed to resolve entry for package "@open-data-v/base". The package may have incorrect main/module/exports specified in its package.json.
Failed to resolve entry for package "@open-data-v/base". The package may have incorrect main/module/exports specified in its package.json. (x2)
Failed to resolve entry for package "@open-data-v/base". The package may have incorrect main/module/exports specified in its package.json. (x3)
Failed to resolve entry for package "@open-data-v/designer". The package may have incorrect main/module/exports specified in its package.json.`

进行的操作
`pnpm install`
`pnpm dev`

环境
`Node.js v18.19.1.`
`pnpm 8.15.4`
`npm 10.2.4`

**Comment by AnsGoo** [comment]
如果使用源码构建请先执行pnpm run build:lib 再pnpm install
